packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  dev:
    '@antfu/eslint-config': ^4.19.0
    '@antfu/ni': ^25.0.0
    '@types/json-schema': ^7.0.15
    '@types/node': ^24.1.0
    bumpp: ^10.2.0
    eslint: ^9.31.0
    lint-staged: ^16.1.2
    pnpm: ^10.13.1
    simple-git-hooks: ^2.13.0
    tsx: ^4.20.3
    typescript: ^5.8.3
    unbuild: ^3.6.0
    vite: ^7.0.6
  prod:
    json-schema-to-typescript-lite: ^15.0.0
    ohash: ^2.0.11
  test:
    '@typescript-eslint/eslint-plugin': ^8.38.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-you-dont-need-lodash-underscore: ^6.14.0
    vitest: ^3.2.4
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
