packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  dev:
    '@antfu/eslint-config': ^4.10.1
    '@antfu/ni': ^24.2.0
    '@types/json-schema': ^7.0.15
    '@types/node': ^22.13.10
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    pnpm: ^10.6.3
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.2
  prod:
    json-schema-to-typescript-lite: ^14.1.0
    ohash: ^2.0.11
  test:
    '@typescript-eslint/eslint-plugin': ^8.26.1
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-import-x: ^4.6.1
    eslint-plugin-jsx-a11y: ^6.10.2
    vitest: ^3.0.8
onlyBuiltDependencies:
  - esbuild
